version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "yourpassword"
      MYSQL_DATABASE: "gotexas"
      MYSQL_USER: "gotexas"
      MYSQL_PASSWORD: "yourpassword"
    volumes:
      - mysql-data:/var/lib/mysql
  
  redis:
    image: redis:6.2
    container_name: redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
  